name: Update Readme File With Medium Blogs
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  update-readme-with-medium:
    name: Update Readme With Latest Medium Article
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch latest medium article
        id: medium
        uses: actions/github-script@v6
        with:
          script: |
            const mediumUsername = 'parameshwarbhat411'
            const response = await fetch('https://medium.com/feed/@${mediumUsername}');
            const rss = await response.text();
            
            const parser = new (require('xml2js')).Parser();
            const feed = await parser.parseStringPromise(rss);
            
            const latestArticle = feed.rss.channel[0].item[0];
            const title = latestArticle.title[0]
            const links = latestArticle.link[0]
            
            console.log(`Fetched article: ${title} - ${link}`);
            
            return { title, link };

      - name: Update Readme
        run: |
          sed -i "s|\[Latest Medium Article\].*|[Latest Medium Article](${{
            steps.medium.outputs.link
          }}) - ${{ steps.medium.outputs.title }}|" README.md

      - name: Commit changes
        run: |
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add README.md
            git commit -m "Update README with latest Medium article"
            git push